GET http://127.0.0.1:8000/api/users
Accept: application/json
Content-Type: application/json

{

}

###
GET http://127.0.0.1:8000/api/users/97a1c076-aa6e-4ac9-aed3-916a1fbd6b33
Accept: application/json
Content-Type: application/json

{

}
###
GET http://127.0.0.1:8000/api/files
Accept: application/json
Content-Type: application/json

{

}

###
POST  http://127.0.0.1:8000/api/register
Accept: application/json
Content-Type: application/json

{
  "email": "user@test1.com",
  "password": "yourpassword"
}

###
POST  http://127.0.0.1:8000/api/login
Accept: application/json
Content-Type: application/json

{
  "email": "user@test1.com",
  "password": "yourpassword"
}

###
DELETE  http://127.0.0.1:8000/api/delete/5df10960-8ce2-45ea-8fef-ba8a7603c291
Content-Type: application/json
